services:
  - type: web
    name: goldbuyersusa-server
    region: oregon
    plan: free
    branch: main
    rootDir: server
    runtime: node
    buildCommand: npm install --legacy-peer-deps
    startCommand: node app.js
    envVars:
      - key: NODE_VERSION
        value: "20.19.0"
      - key: NODE_ENV
        value: production
      - key: API_NAME
        value: GOLDBUYERSUSA
      - key: DB_DIALECT
        value: postgres
      - key: DB_HOST
        value: dpg-d963rhks728c73f4hq60-a
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: goldbuyersusa_db
      - key: DB_USERNAME
        value: goldbuyersusa_db_user
      - key: DB_PASSWORD
        value: "1WfVW3dUW0pnRBFlWdyEhp4sV7BsEpGZ"
      - key: SYNC
        value: "false"
      - key: REDIS_HOST
        value: red-d9641usvikkc73dtgiog
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        value: kd3LBK2MPv6y7Rd7TMgz4Sbfc3YhYTKP
      - key: PUBSUB_HOST
        value: red-d9641usvikkc73dtgiog
      - key: PUBSUB_PORT
        value: "6379"
      - key: PUBSUB_PASSWORD
        value: kd3LBK2MPv6y7Rd7TMgz4Sbfc3YhYTKP
      - key: NETWORK
        value: mainnet

  - type: static
    name: goldbuyersusa-web
    region: oregon
    branch: main
    rootDir: web
    buildCommand: npm ci && CI=false npx craco build --max_old_space_size=4096
    staticPublishPath: build
    envVars:
      - key: NODE_VERSION
        value: "20.19.0"
      - key: CI
        value: "false"
      - key: REACT_APP_EXCHANGE_NAME
        value: GOLDBUYERSUSA
      - key: REACT_APP_PUBLIC_URL
        value: https://goldbuyersusa-web.onrender.com
      - key: REACT_APP_SERVER_ENDPOINT
        value: https://goldbuyersusa-server.onrender.com
